export const BREADCRUMB_LABELS: Record<string, string> = {
  dashboard: "Dashboard",
  network: "Network",
  mesh: "Topology",
  nodes: "Nodes",
  services: "Services",
  fidelity: "Fidelity",
  dag: "DAG View",
  circuits: "Circuits",
  zones: "Zones",
  runs: "Runs",
  new: "New",
  options: "Options",
  batch: "Batch",
  history: "History",
  risk: "Risk",
  finance: "Financial",
  docs: "Docs",
  api: "API Reference",
  roadmap: "Roadmap",
  schemas: "Schemas",
  examples: "Examples",
  playbooks: "Playbooks",
  settings: "Settings",
  integrations: "Integrations",
  users: "Users",
  security: "Security",
  observability: "Observability",
  audit: "Audit Logs",
} as const;

export const RAIL_LABEL_FOR_PREFIX: Record<string, string> = {
  "/dashboard": "Dashboard",
  "/network": "Network",
  "/runs": "Lab",
  "/options": "Lab",
  "/risk": "Lab",
  "/finance": "Lab",
  "/docs": "Docs",
  "/settings": "Settings",
} as const;
