export const ROUTES = {
  SIGNIN: "/signin",
  SIGNUP: "/signup",
  DASHBOARD: "/dashboard",
  DASHBOARD_NETWORK_HEALTH: "/dashboard/network-health",
  ANALYTICS: "/analytics",
  ANALYTICS_COMPARISONS: "/analytics/comparisons",
  ANALYTICS_DEEP_STATE: "/analytics/deep-state",
  ANALYTICS_DIAGNOSTICS: "/analytics/diagnostics",
  ANALYTICS_FRONTIER: "/analytics/frontier",
  ANALYTICS_GEOMETRY: "/analytics/geometry",
  ANALYTICS_MEASUREMENTS: "/analytics/measurements",
  ANALYTICS_RANKING: "/analytics/ranking",
  NETWORK: "/network",
  NETWORK_CIRCUITS: "/network/circuits",
  NETWORK_DAG: "/network/dag",
  NETWORK_FIDELITY: "/network/fidelity",
  NETWORK_MESH: "/network/mesh",
  NETWORK_NODES: "/network/nodes",
  NETWORK_SERVICES: "/network/services",
  NETWORK_ZONES: "/network/zones",
  FINANCE: "/finance",
  FINANCE_HISTORY: "/finance/history",
  financeDetail: (id: string) => `/finance/${id}` as const,
  financeQuantum: (id: string) => `/finance/${id}/quantum` as const,
  FINANCE_BENCHMARK: "/finance/benchmark",
  FINANCE_EXECUTION: "/finance/execution",
  FINANCE_FRONTIER: "/finance/frontier",
  FINANCE_STATES: "/finance/states",
  OPTIONS: "/options",
  OPTIONS_BATCH: "/options/batch",
  OPTIONS_HISTORY: "/options/history",
  optionsDetail: (id: string) => `/options/${id}` as const,
  RISK: "/risk",
  RISK_HISTORY: "/risk/history",
  riskDetail: (id: string) => `/risk/${id}` as const,
  RUNS: "/runs",
  RUNS_NEW: "/runs/new",
  runDetail: (id: string) => `/runs/${id}` as const,
  runFragmentFlow: (id: string) => `/runs/${id}/fragment-flow` as const,
  DOCS: "/docs",
  DOCS_API: "/docs/api",
  DOCS_EXAMPLES: "/docs/examples",
  DOCS_PLAYBOOKS: "/docs/playbooks",
  DOCS_ROADMAP: "/docs/roadmap",
  DOCS_SCHEMAS: "/docs/schemas",
  SETTINGS: "/settings",
  SETTINGS_AUDIT: "/settings/audit",
  SETTINGS_INTEGRATIONS: "/settings/integrations",
  SETTINGS_OBSERVABILITY: "/settings/observability",
  SETTINGS_SECURITY: "/settings/security",
  SETTINGS_USERS: "/settings/users",
} as const;
